//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WYRMS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules
    {
        public Modules()
        {
            this.Modules1 = new HashSet<Modules>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string LinkUrl { get; set; }
        public bool IsMenu { get; set; }
        public int Code { get; set; }
        public string Description { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<Modules> Modules1 { get; set; }
        public virtual Modules Modules2 { get; set; }
    }
}
